// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCGePqz5cvhemVZvYPYjXpPAlPRish0QA',
    appId: '1:243531171881:web:f79192cd047e3da2593438',
    messagingSenderId: '243531171881',
    projectId: 'insurevis',
    authDomain: 'insurevis.firebaseapp.com',
    storageBucket: 'insurevis.firebasestorage.app',
    measurementId: 'G-ZCS0M65Q51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEFh9_mRYO4qpw8uQgh9-192_tEVa7anQ',
    appId: '1:243531171881:android:005c8bcb6ecb74f1593438',
    messagingSenderId: '243531171881',
    projectId: 'insurevis',
    storageBucket: 'insurevis.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu679xFmLDPVFmz0r96usAs2D29RA9GUM',
    appId: '1:243531171881:ios:b257fc56b174269c593438',
    messagingSenderId: '243531171881',
    projectId: 'insurevis',
    storageBucket: 'insurevis.firebasestorage.app',
    iosBundleId: 'com.example.insurevis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu679xFmLDPVFmz0r96usAs2D29RA9GUM',
    appId: '1:243531171881:ios:b257fc56b174269c593438',
    messagingSenderId: '243531171881',
    projectId: 'insurevis',
    storageBucket: 'insurevis.firebasestorage.app',
    iosBundleId: 'com.example.insurevis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCGePqz5cvhemVZvYPYjXpPAlPRish0QA',
    appId: '1:243531171881:web:146ea83be2f5bdf7593438',
    messagingSenderId: '243531171881',
    projectId: 'insurevis',
    authDomain: 'insurevis.firebaseapp.com',
    storageBucket: 'insurevis.firebasestorage.app',
    measurementId: 'G-1LKZ5QENCP',
  );
}
